-- MySQL Script generated by MySQL Workbench
-- 2022年04月05日 星期二 11时45分20秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mobile_pay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mobile_pay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobile_pay` ;
USE `mobile_pay` ;

-- -----------------------------------------------------
-- Table `mobile_pay`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `passport_number` VARCHAR(15) NOT NULL,
  `country` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `passport_photo` VARCHAR(50) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `payment_password` VARCHAR(6) NOT NULL,
  `state` ENUM('frozen', 'unverified', 'normal') NOT NULL DEFAULT 'unverified',
  `money_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `frozen_money` DECIMAL(19,4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `passport_photo_UNIQUE` (`passport_photo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`admin` (
  `admin_account` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`admin_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`merchant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`merchant` (
  `merchant_id` INT NOT NULL AUTO_INCREMENT,
  `merchant_user_id` INT NOT NULL,
  `merchant_name` VARCHAR(50) NOT NULL,
  `merchant_license` VARCHAR(50) NOT NULL,
  `merchant_license_photo` VARCHAR(200) NOT NULL,
  `merchant_phone_number` VARCHAR(20) NOT NULL,
  `merchant_logo` VARCHAR(200) NULL,
  `merchant_email` VARCHAR(30) NOT NULL,
  `frozen_money` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `money_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `state` ENUM('frozen', 'unverified', 'normal') NULL DEFAULT 'unverified',
  PRIMARY KEY (`merchant_id`),
  UNIQUE INDEX `merchant_license_UNIQUE` (`merchant_license` ASC) VISIBLE,
  UNIQUE INDEX `merchant_user_id_UNIQUE` (`merchant_user_id` ASC) VISIBLE,
  UNIQUE INDEX `merchant_license_photo_UNIQUE` (`merchant_license_photo` ASC) VISIBLE,
  UNIQUE INDEX `merchant_phone_number_UNIQUE` (`merchant_phone_number` ASC) VISIBLE,
  CONSTRAINT `fk_merchant_1`
    FOREIGN KEY (`merchant_user_id`)
    REFERENCES `mobile_pay`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`transfer` (
  `transfer_id` INT NOT NULL AUTO_INCREMENT,
  `source_user_id` INT NOT NULL,
  `target_user_id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `amount` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`transfer_id`),
  UNIQUE INDEX `source_user_id_UNIQUE` (`source_user_id` ASC) VISIBLE,
  UNIQUE INDEX `target_user_id_UNIQUE` (`target_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `mobile_pay`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_2`
    FOREIGN KEY (`target_user_id`)
    REFERENCES `mobile_pay`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`pay` (
  `pay_id` INT NOT NULL AUTO_INCREMENT,
  `source_user_id` INT NOT NULL,
  `target_merchant_id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `state` ENUM('normal', 'refunded') NOT NULL DEFAULT 'refunded',
  `amount` DECIMAL(19,4) NOT NULL,
  `fee` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`pay_id`),
  INDEX `fk_pay_1_idx` (`source_user_id` ASC) VISIBLE,
  INDEX `fk_pay_2_idx` (`target_merchant_id` ASC) VISIBLE,
  CONSTRAINT `fk_pay_1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `mobile_pay`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_2`
    FOREIGN KEY (`target_merchant_id`)
    REFERENCES `mobile_pay`.`merchant` (`merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`refund` (
  `refund_id` INT NOT NULL AUTO_INCREMENT,
  `pay_id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`refund_id`),
  UNIQUE INDEX `pay_id_UNIQUE` (`pay_id` ASC) VISIBLE,
  CONSTRAINT `fk_refund_1`
    FOREIGN KEY (`pay_id`)
    REFERENCES `mobile_pay`.`pay` (`pay_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`user_export_merchant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`user_export_merchant` (
  `export_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`export_id`),
  INDEX `fk_user_export_merchant_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_export_merchant_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mobile_pay`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_pay`.`merchant_export_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_pay`.`merchant_export_user` (
  `export_id` INT NOT NULL AUTO_INCREMENT,
  `merchant_id` INT NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`export_id`),
  INDEX `fk_merchant_export_user_1_idx` (`merchant_id` ASC) VISIBLE,
  CONSTRAINT `fk_merchant_export_user_1`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `mobile_pay`.`merchant` (`merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
